# Publications missing from ORCID auto-import

- id: doi:10.1016/j.bioorg.2024.107840
  image: 
  tags:
    - pseudomonas
    - antivirulence
    - medicinal chemistry

- id: doi:10.1371/journal.ppat.1010307
  tags:
    - antibiotic tolerance
    - microbiology

- id: doi:10.1021/bc500200t
  tags:
    - bioconjugate chemistry
    - nanoparticles

# Manual entries for publications without DOI metadata available

- title: Using Untargeted Mass Spectrometry Based Proteomics to Identify Putative Microprotein Biomarkers from Patient Tampons
  authors:
    - G. T. Luu
    - C. A. Fihn
    - L. M. Sanchez
  publisher: Methods in Molecular Biology
  date: 2026-01-01
  type: paper
  tags:
    - proteomics
    - mass spectrometry
    - microbiology

- title: Investigation of an ALDH1A1-Specific Inhibitor for Suppression of Weight Gain in a Diet-Induced Mouse Model of Obesity
  authors:
    - M. Haenisch
    - T. Nguyen
    - C. A. Fihn
    - A. S. Goldstein
    - J. K. Amory
    - P. Treuting
    - T. Brabb
    - J. Paik
  publisher: International Journal of Obesity
  date: 2021-01-01
  type: paper
  tags:
    - metabolism
    - obesity biology

- title: Screening Serine/Threonine and Tyrosine Kinase Inhibitors for Histidine Kinase Inhibition
  authors:
    - K. E. Wilke
    - C. A. Fihn
    - E. E. Carlson
  publisher: Bioorganic & Medicinal Chemistry
  date: 2018-01-01
  type: paper
  tags:
    - histidine kinases
    - kinase inhibitors
    - chemical biology
